# Generated by Django 5.2.12 on 2026-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('dinner_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('event', models.CharField(blank=True, default='', max_length=50, verbose_name='用事')),
                ('kondate', models.CharField(blank=True, default='', max_length=256, verbose_name='献立')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '献立',
                'verbose_name_plural': '献立',
                'db_table': 'dinner',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(blank=True, default='', max_length=256, verbose_name='残りの食材')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '食材メモ',
                'verbose_name_plural': '食材メモ',
                'db_table': 'ingredients',
            },
        ),
    ]
